[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 4321
  publish = "dist"
  autoLaunch = false
  framework = "astro"

[[redirects]]
  from = "/netlify-rewrite-to-ssr-page"
  to = "/ssr-page-1"
  status = 200
  force = true

[[redirects]]
  from = "/netlify-rewrite-to-ssg-page"
  to = "/ssg-page-a"
  status = 200
  force = true
